export enum ApiErrorCode {
    INTERNAL_SERVER_ERROR,

    INVALID_BODY,
    INVALID_BODY_DATE_VALUE,
    ERROR_WHILE_PURGING_BODY,

    PROVIDED_ID_NOT_FOUND,
    ISBN_NOT_FOUND,

    LABELS_PARENT_DISCENDANT_OF_CHILD,

    USER_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    INVALID_LOGIN,
    USER_NOT_VERIFIED,
    INVALID_AUTH_TOKEN,
    USER_UNAUTHORIZED,
    USERNAME_NOT_EXISTS,
    EMAIL_NOT_EXISTS,
    USERNAME_NOT_FOUND,
    INVALID_TOKEN,

    FRIEND_DOES_NOT_EXIST,
    USER_IS_ALREADY_FRIEND,
    USER_CANNOT_BE_FRIEND_WITH_HIMSELF,
    
    CHAT_ALREADY_EXISTS
}

export interface ApiError {
    message: string;
    code: ApiErrorCode;
}